HomeRent/HomeRent/Models/HouseRent.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeRent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseRent
    {
        public int ID { get; set; }
        public int FlatID { get; set; }
        public int AreaID { get; set; }
        public int CategoryID { get; set; }
        public int Rent_PSFT { get; set; }
        public Nullable<int> FlatSize { get; set; }
        public Nullable<int> TotalRent { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Category Category { get; set; }
        public virtual Flat Flat { get; set; }
    }
}

HomeRent/HomeRent/Controllers/FlatController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HomeRent.Models;

namespace HomeRent.Controllers
{
    public class FlatController : Controller
    {
        private HomeRentDB db = new HomeRentDB();

        // GET: /Flat/
        public ActionResult Index()
        {
            var uid = Convert.ToInt32(Session["ID"]);
            var flats = db.Flats.Include(f => f.House).Where(flt=>flt.House.UserID == uid);
            return View(flats.ToList());
        }
        public string GetFlatSize(int id=0)
        {
            return db.Flats.Find(id).Size.ToString();
        }
        

        public ActionResult List()
        {
            var flats = db.Flats.Include(f => f.House);
            return View(flats.ToList());
        }

        // GET: /Flat/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flat flat = db.Flats.Find(id);
            if (flat == null)
            {
                return HttpNotFound();
            }
            return View(flat);
        }

        // GET: /Flat/Create
        public ActionResult Create()
        {
            var uid = Convert.ToInt32(Session["ID"]);
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name");
            ViewBag.HouseID = new SelectList(db.Houses.Where(hs=>hs.UserID == uid), "ID", "Name");
            return View();
        }

        // POST: /Flat/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public ActionResult Create([Bind(Include="ID,Name,Size,HouseID,CategoryID")] Flat flat)
        {
            
            if (ModelState.IsValid)
            {
                //Session["ID"] = HouseID;
                db.Flats.Add(flat);
                db.SaveChanges();
                //return RedirectToAction("Create","HouseRent");
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", flat.CategoryID);
            ViewBag.HouseID = new SelectList(db.Houses.Where(h=>h.UserID==flat.HouseID), "ID", "Name");
            
            return View(flat);
        }

        // GET: /Flat/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flat flat = db.Flats.Find(id);
            if (flat == null)
            {
                return HttpNotFound();
            }
            ViewBag.HouseID = new SelectList(db.Houses, "ID", "Name", flat.HouseID);
            return View(flat);
        }

        // POST: /Flat/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,Name,Size,HouseID")] Flat flat)
        {
            if (ModelState.IsValid)
            {
                db.Entry(flat).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.HouseID = new SelectList(db.Houses, "ID", "Name", flat.HouseID);
            return View(flat);
        }

        // GET: /Flat/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Flat flat = db.Flats.Find(id);
            if (flat == null)
            {
                return HttpNotFound();
            }
            return View(flat);
        }

        // POST: /Flat/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Flat flat = db.Flats.Find(id);
            db.Flats.Remove(flat);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HomeRent/HomeRent/Controllers/HouseRentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HomeRent.Models;

namespace HomeRent.Controllers
{
    
    public class HouseRentController : Controller
    {
        private HomeRentDB db = new HomeRentDB();
        User user=new User();
      
        // GET: /HouseRent/
        public ActionResult Index()
        {
            var uid = Convert.ToInt32(Session["ID"]);

            var houserents = db.HouseRents.Where(h=>h.Flat.House.UserID==uid).Include(h => h.Area).Include(h => h.Category).Include(h => h.Flat);
            return View(houserents.ToList());
        }

        public JsonResult GetCategory(int id = 0)
        {
            return Json(new SelectList(db.Categories.Where(c => c.ID == id), "ID", "Name"));
        }


        public string GetRent(int catid = 0, int arid = 0)
        {
            return db.FixRents.Where(fr => fr.CategoryID == catid && fr.AreaID == arid).FirstOrDefault().Rent.ToString();
        }

       
        // GET: /HouseRent/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HouseRent houserent = db.HouseRents.Find(id);
            if (houserent == null)
            {
                return HttpNotFound();
            }
            return View(houserent);
        }

        // GET: /HouseRent/Create
        public ActionResult Create()
        {
            var uid = Convert.ToInt32(Session["ID"]);
            
            ViewBag.AreaID = new SelectList(db.Areas, "ID", "Name");
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name");
            ViewBag.FlatID = new SelectList(db.Flats.Where(f => f.House.UserID == uid), "ID", "Name");
            ViewBag.HouseID = new SelectList(db.Houses.Where(h => h.UserID == uid), "ID", "Name");
      
            return View();
        }

        // POST: /HouseRent/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="ID,Rent_PSFT,FlatID,AreaID,CategoryID,FlatSize,TotalRent")] HouseRent houserent,Area area)
        {
            if (ModelState.IsValid)
            {
                db.HouseRents.Add(houserent);
                db.SaveChanges();
                
                return RedirectToAction("Index");
            }
          
            ViewBag.AreaID = new SelectList(db.Areas, "ID", "Name", houserent.AreaID);
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", houserent.CategoryID);
            ViewBag.FlatID = new SelectList(db.Flats, "ID", "Name", houserent.FlatID);
            //ViewBag.HouseID = new SelectList(db.Houses, "ID", "Name", houserent.HouseID);
            return View(houserent);
        }

        // GET: /HouseRent/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HouseRent houserent = db.HouseRents.Find(id);
            if (houserent == null)
            {
                return HttpNotFound();
            }
            ViewBag.AreaID = new SelectList(db.Areas, "ID", "Name", houserent.AreaID);
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", houserent.CategoryID);
            ViewBag.FlatID = new SelectList(db.Flats, "ID", "Name", houserent.FlatID);
            return View(houserent);
        }

        // POST: /HouseRent/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="ID,MinRent_PSFT,MaxRent_PSFT,FlatID,AreaID,CategoryID")] HouseRent houserent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(houserent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AreaID = new SelectList(db.Areas, "ID", "Name", houserent.AreaID);
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "Name", houserent.CategoryID);
            ViewBag.FlatID = new SelectList(db.Flats, "ID", "Name", houserent.FlatID);
            return View(houserent);
        }

        // GET: /HouseRent/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HouseRent houserent = db.HouseRents.Find(id);
            if (houserent == null)
            {
                return HttpNotFound();
            }
            return View(houserent);
        }

        // POST: /HouseRent/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HouseRent houserent = db.HouseRents.Find(id);
            db.HouseRents.Remove(houserent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HomeRent/HomeRent/Views/HouseRent/Create.cshtml
@using HomeRent.Controllers
@using HomeRent.Models
@model HomeRent.Models.HouseRent

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_PublicLayout.cshtml";
    
}
<h2>Create</h2>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
    var rent = 0,size = 0;
    $(document).ready(function () {        
        $("#Area").change(function() {
            $("#CategoryID").empty();
            $("#CategoryID").append('<option value="0">Select One</option>');

            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetCategory", "HouseRent")',
                dataType: 'json',
                data: { id: $("#Area").val() },
                success: function(states) {
                    $.each(states, function(i, state) {
                        $("#Category").append('<option value="' + state.Value + '">' +
                            state.Text + '</option>');
                    });
                },
                error: function(ex) {
                    alert('Failed to retrieve states.' + ex);
                }
            });
            return false;
        });

        $("#CategoryID").change(function() {
            $("#Rent_PSFT").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetRent", "HouseRent")',
                dataType: 'text',
                data: { arid: $("#AreaID").val(), catid: $("#CategoryID").val() },
                success: function(states) {
                    $("#Rent_PSFT").val(states);
                    rent = parseInt(states);
                    //$('[name="TotalRent"]').val(size * rent);
                },
                error: function(ex) {
                    alert('Failed to retrieve states.' + ex);
                }
            });
            return false;
        });

        $("#HouseID").change(function () {
            $("#FlatID").empty();
            $("#FlatID").append('<option value="0">Select One</option>');

            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetFlat", "RentSlip")',
                dataType: 'json',
                data: { id: $("#HouseID").val() },
                success: function (states) {
                    $.each(states, function (i, state) {
                        $("#FlatID").append('<option value="' + state.Value + '">' +
                            state.Text + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve states.' + ex);
                }
            });
            return false;
        });
        $("#FlatID").change(function() {
            $("#FlatSize").empty();
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetFlatSize", "Flat")',
                dataType: 'text',
                data: { id: $("#FlatID").val() },
                success: function(states) {
                    $("#FlatSize").val(states);
                    size = parseInt(states);
                    $('[name="TotalRent"]').val(size * rent);
                },

                error: function(ex) {
                    alert('Failed to retrieve states.' + ex);
                }
            });
            return false;
        });
        
    });
</script>
<form method="POST" class="form-horizontal">
    @Html.AntiForgeryToken()
    <div class="row" id="demo">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <div class="panel-title">

                    <center><strong> House Rent </strong><br><small>Register below</small></center>
                </div>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">Area</label>
                    <div class="col-md-6">
                        @Html.DropDownList("AreaID", null, "Select One", new { @class = "form-control" })

                    </div>
                </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">Category</label>
                        <div class="col-md-6">
                            @Html.DropDownList("CategoryID", null, "Select One", new { @class = "form-control" })

                        </div>
                    </div>
                  
                <div class="form-group">
                    <label class="col-md-3 control-label">Rent</label>
                    <div class="col-md-6">
                        @Html.TextBoxFor(x => x.Rent_PSFT, new { @class = "form-control",@readonly = "readonly" })
                          

                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label">House</label>
                    <div class="col-md-6">
                        @Html.DropDownList("HouseID", null, "Select One", new { @class = "form-control" })
                    </div>
                </div>
                              
                                <div class="form-group">
                                    <label class="col-md-3 control-label">Flat</label>
                                    <div class="col-md-6">
                                        @Html.DropDownList("FlatID", null, "Select One", new { @class = "form-control" })

                                    </div>
                                    </div>
                                   
                    <div class="form-group">
                        <label class="col-md-3 control-label">Flat Size</label>
                        <div class="col-md-6">
                            @Html.TextBoxFor(fl => fl.FlatSize, new { @class = "form-control", @readonly = "readonly" })
                            
                        </div>
                    </div>

                                      
                                        <div class="form-group">
                                            <label class="col-md-3 control-label">TotalRent</label>
                                            <div class="col-md-6">
                                               @Html.TextBoxFor(t => t.TotalRent, new { @class = "form-control", @readonly = "readonly" })
                                            
                                            </div>
                                            </div>
                                         
                                            <div class="form-group">
                                                <label class="col-md-3 control-label"></label>
                                                <div class="col-md-6">
                                                   <center> <button type="submit" id="btnSave" class="btn btn-primary">Save</button></center>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                           
                       
</form>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

HomeRent/HomeRent/Views/HouseRent/Delete.cshtml
@model HomeRent.Models.HouseRent

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HouseRent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Rent_PSFT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flat.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Area.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Area.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Area.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Flat.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flat.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HomeRent/HomeRent/Views/HouseRent/Details.cshtml
@model HomeRent.Models.HouseRent

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>HouseRent</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MinRent_PSFT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MinRent_PSFT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxRent_PSFT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxRent_PSFT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Area.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Area.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Flat.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flat.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HomeRent/HomeRent/Views/HouseRent/Edit.cshtml
@model HomeRent.Models.HouseRent

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>HouseRent</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.MinRent_PSFT, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MinRent_PSFT)
                @Html.ValidationMessageFor(model => model.MinRent_PSFT)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxRent_PSFT, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxRent_PSFT)
                @Html.ValidationMessageFor(model => model.MaxRent_PSFT)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FlatID, "FlatID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("FlatID", String.Empty)
                @Html.ValidationMessageFor(model => model.FlatID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AreaID, "AreaID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AreaID", String.Empty)
                @Html.ValidationMessageFor(model => model.AreaID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", String.Empty)
                @Html.ValidationMessageFor(model => model.CategoryID)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HomeRent/HomeRent/Views/HouseRent/Index.cshtml
@using System.Security.Policy
@model IEnumerable<HomeRent.Models.HouseRent>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_PublicLayout.cshtml";
}

<center><div class="col-md-12" style="color: royalblue"><h2>House Rent Details</h2></div></center>

<p style="color: royalblue">
    <center> @Html.ActionLink("Create New House Rent", "Create")</center>
</p>
<table class="table" border="1">
    <tr>
        
        
        <th>
            @Html.DisplayName("Area")
        </th>
        <th>
           @Html.DisplayName("Category")
        </th>
        <th>
            @Html.DisplayName("House Name")
        </th>
        <th>
            @Html.DisplayName("Flat Name")
        </th>
        <th>
            @Html.DisplayName("Flat Size")
        </th>
        <th>
            @Html.DisplayName("Rent_PSFT")
        </th>
        <th>
            @Html.DisplayName("Total Rent")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        
        
        <td>
            @Html.DisplayFor(modelItem => item.Area.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Flat.House.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Flat.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Flat.Size)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rent_PSFT)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalRent)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>